name: simulator
description: The simulator from the Rohme package, with picosecond resolution and delta cycle microtask scheduling.
version: 1.0.0
repository: https://github.com/AdamRose66/simulator.git

environment:
  sdk: ^3.2.4

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
